apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: redis-queue-worker
  namespace: keda-demo
spec:
  scaleTargetRef:
    name: keda-worker
  pollingInterval: 10
  cooldownPeriod: 60
  minReplicaCount: 0
  maxReplicaCount: 8
  triggers:
    - type: redis
      metadata:
        address: redis.keda-demo.svc.cluster.local:6379
        listName: work-items
        listLength: "25"
        databaseIndex: "0"
